# Generated by Django 3.0.5 on 2020-04-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
                ('job_title', models.CharField(max_length=250)),
                ('actual_job', models.BooleanField(default=False)),
                ('description', models.TextField()),
            ],
        ),
    ]
