# Generated by Django 3.0.5 on 2020-04-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='percentage',
            field=models.PositiveSmallIntegerField(default=60),
        ),
    ]
